### ISSUE TITLE
Doesn't work for image or voice messages

### ISSUE THREAD

**Issue by paras-malhotra** [grammyjs/auto-retry#13]
When we use this package and send an image (perhaps also applies for voice messages), it errors out with: 

> GrammyError: Call to 'sendPhoto' failed! (400: Bad Request: there is no photo in the request)

It does this for all image and voice messages sent - not just the ones that failed or were retried.

**Comment by KnorpelSenf** [comment]
It works for me, so the issue is not correct the way you describe it.

If you think you found a bug, then you need to at least provide some information about how to reproduce it.

**Comment by paras-malhotra** [comment]
I see, perhaps it may have been something to do with my setup. I'll reopen when I get some time to reproduce the error on a fresh Grammy app.
