### ISSUE TITLE
Conflict with the `runner` plugin in a NestJS app

### ISSUE THREAD

**Issue by andrew-sol** [grammyjs/auto-retry#18]
When this plugin is used in a NestJS app, the following promise will never resolve:

```ts
await this.runnerHandle.stop(); // hangs forever, though the bot stops fetching updates
```

Because of this the app never recompiles when you change the code.

Removing the following line makes the app behave normally:
```ts
this.bot.api.config.use(autoRetry());
```

See the reproduction repo: https://github.com/andrew-sol/grammy-runner-reproduction (`app.service.ts` file)
The repo has two branches: `main` and `without-nest`.

The bug is reproducible only on the `main` branch. The `without-nest` branch contains the same setup but without the NestJS framework and TypeScript.

Related: https://github.com/grammyjs/runner/issues/22

**Comment by KnorpelSenf** [comment]
Thanks for the short repro, that made it easy to reproduce the issue. The auto-retry plugin did handle signals correctly while waiting between retries, but it incorrectly did not rethrow errors when actual requests were aborted.

#19 fixes that. Could you leave a review?
